panoptes_client/panoptes.py

Sometimes this header is missing (I suspect the ELB is dropping it...)
and we don't want to return None if there really is a response.

Don't rely on the response having a Content-Length header

---

panoptes_client/panoptes.py
panoptes_client/project.py

Talk exports still not supported. They'll come soon -- I'm intending to abstract away the fact that Talk exports work differently to the others, so it'll work like the following:
```python
project = Project(...)
project.get_export('classifications')
project.get_export('subjects')
project.get_export('talk_comments')
```

Support for all exports

---

README.md
panoptes_client/panoptes.py
panoptes_client/project_preferences.py

A project owner can update the "settings" attribute of ProjectPreferences. #save() doesn't work here because they won't have permission to update anything else, so I added a method.

Project owners can update ProjectPreference settings

---

setup.py

Earlier versions don't support the `json` request parameter

Specify minimum requests version

---

panoptes_client/panoptes.py

```if not self.bearer_token or self.bearer_expires > datetime.now():```
would always evaluate True on the second part because the `not` doesn't apply to both. Flipped the sign so that this if statement evaluates true if there is no bearer token or if it is expired.

Flipped sign on expiration check

---

panoptes_client/__init__.py
panoptes_client/panoptes.py
panoptes_client/project.py
panoptes_client/project_role.py
panoptes_client/user.py

Example usage:
```python
>>> from panoptes_client import Project
>>> p = Project.find(slug='zooniverse/shakespeares-world')
>>> p.collaborators()
[<User 7>, <User 299778>, <User 245>, <User 10>, <User 1490760>, <User 321028>, <User 352990>, <User 1412010>, <User 1414358>, <User 828029>, <User 1410251>, <User 1410955>, <User 255>, <User 246>, <User 1813>, <User 1370867>, <User 1395487>, <User 219>, <User 1405910>, <User 6>, <User 1404044>, <User 322786>, <User 1>]
>>> p.collaborators('owner')
[<User 1>]
>>> p.collaborators('expert')
[<User 1414358>, <User 1410251>, <User 1410955>, <User 1370867>, <User 1395487>]
>>> p.collaborators('owner', 'expert')
[<User 1414358>, <User 1410251>, <User 1410955>, <User 1370867>, <User 1395487>, <User 1>]
```

Add Project.collaborators() and ProjectRole

---

panoptes_client/workflow.py

Added ['tasks', 'first_task', 'configuration'] to _edit_attributes in Workflow class in workflow.py
Seems to let you edit workflow objects as expected (tested on panoptes-staging.zooniverse.org)

Added editable attributes to workflow.py allowing editing of workflow

---

README.md
panoptes_client/workflow.py

I've updated the python client and docs/readme so workflows can have subjectsets linked to them.

Support for adding subjectsets to workflows

---

panoptes_client/panoptes.py

Specifically, CloudFront rejects GET requests with empty JSON bodies.

Don't submit empty JSON by default

---

panoptes_client/utils.py

e.g. if it's erroneously been passed as a named argument.

Raise TypeError if positional batchable argument is missing

---

panoptes_client/panoptes.py

The behaviour of map is different in Python 3

Fix: Return a list of linked objects instead of a map

---

panoptes_client/panoptes.py

Instantiate them with an ID, rather than using `.find()`, and the client will automatically do a `GET` the first time you access any attributes.
This means, for example, when iterating over `Project.links.subject_sets` we don't necessarily need to get all of them.
An example of this in action, with debugging print of HTTP requests:
```python
>>> from panoptes_client import Project
>>> p = Project.find(4115)
GET https://www.zooniverse.org/api/projects/4115
>>> p.links.subject_sets
[<SubjectSet 9186>, <SubjectSet 9245>, <SubjectSet 9126>, <SubjectSet 9127>, <SubjectSet 9128>, <SubjectSet 9150>, <SubjectSet 9223>]
>>> p.links.subject_sets[0].display_name
GET https://www.zooniverse.org/api/subject_sets/9186
'Planet9 PNG Take 2'
>>> p = Project(4115)
>>> p
<Project 4115>
>>> p.slug
GET …
```

Allow lazy loading of objects

---

Dockerfile.dev
Dockerfile.dev2
panoptes_client/panoptes.py
panoptes_client/workflow.py
panoptes_client/workflow_version.py

Adds a `Workflow.versions` property. Example usage:
```python
>>> from panoptes_client import Workflow
>>> w = Workflow(43)
>>> v = list(w.versions)
>>> v[0].workflow
<Workflow 43>
>>> v[0].changeset
{'tasks': [{'T1': {'help': 'T1.help', 'type': 'drawing', 'tools': [{'type': 'point', 'color': '#00ff00', 'label': 'T1.tools.0.label', 'details': []}], 'instruction': 'T1.instruction'}, 'T2': {'help': 'T2.help', 'type': 'single', 'answers': [], 'question': 'T2.question'}, 'T3': {'type': 'survey', 'images': {}, 'choices': {}, 'questions': {}, 'choicesOrder': [], 'questionsOrder': [], 'characteristics': {}, 'characteristicsOrder': []}}, {'T1': {'help': 'T1.help', 'type': 'drawing', 'tools': [{'type': 'point', 'color': '#00ff00', 'label': 'T1.tools.0.label', 'details': []}], 'instruction': …
```

Add Workflow versions

---

panoptes_client/panoptes.py

closes #83 
On create actions, save the resource attributes and etag from the api response. On updates force a reload if the resource is used again.

avoid reloading resource after create actions

---

panoptes_client/panoptes.py

Treat bearer token as expired if it is about to expire in the next minute.
I'm experiencing an edge case where the bearer token expires before firing a request, but after I call get_bearer_token in the python client. I'm working with caesar to PUT reductions made by SWAP from a classification stream. SWAP calls get_bearer_token every time a request is made to caesar, so the token refresh and expiration checking is handled by the python client. SWAP ran for at least 8 hours without issues, meaning that the token was being refreshed periodically by the python client.
The client refreshed the bearer token at 6:52:29, and a request made at 8:52:29 returned a 401 from caesar. The bearer token expired in the time it took to build and fire the request. I'm making requests externally from the …

Add buffer to bearer token expiration check

---

panoptes_client/panoptes.py
panoptes_client/tests/test_bearer_expiry.py
setup.py

The bearer token buffer in the last pull request subtracted the buffer from the clock, meaning the token would appear to expire AFTER it actually expired. 
This pull request makes the bearer expiration check an independent testable function. It also fixes the buffer direction by adding time to the clock, making it appear that the clock is later and expiring the token early.
Sorry about the bad code earlier, I should have tested it better.

Bearer token buffer

---

panoptes_client/panoptes.py

Using current functionality, logging in requires a user to manually
enter their credentials within their script (using the login() function or
by passing credentials to the Panoptes object initializer), or to store them as
environment variables in `PANOPTES_USERNAME` and `PANOPTES_PASSWORD`.
This commit adds functionality for an interactive login. This would allow a
user to enter their credentials manually when running a script that doesn't
involve storing the credentials in a static file or in an environment
variable.

Interactive login

---

panoptes_client/collection.py

Gravity Spy needs to be able to programmatically create collections, so being able to edit the project and default_subject links are required.

Editable collection project link

---

panoptes_client/panoptes.py

* Do not automatically create a global client, except when calling
`Panoptes.connect()`.
* Use threading.local() to store global client, rather than a class
attribute.
* Make the Panoptes class a context manager so new clients can be
created using the `with` statement.
This is completely untested at the moment. Docstrings will also need to be updated before merging.

Make global client thread safe

---

panoptes_client/panoptes.py

Ensure we have distinct applications for the different clients, PFE, python, etc. I've setup the new applications to have the correct rights and can be located at:
+ https://panoptes-staging.zooniverse.org/oauth/applications/44
+ https://panoptes.zooniverse.org/oauth/applications/97
Prompted by https://github.com/zooniverse/Panoptes/pull/2847 - this will require me to audit and change each app's confidential attribute according to how it's being used.

switch to distinct oauth apps for the python client

---

panoptes_client/subject.py
setup.py

Using the redo module. Also use this module for retrying media uploads.
Also fixes a TypeError introduced in 1.0.2.
This will need to wait for mozilla-releng/redo#43 to be fixed, because otherwise
subject uploads will flood the terminal with logging messages.

Retry creating subjects on failure

---

panoptes_client/panoptes.py
panoptes_client/tests/test_linkresolver.py
panoptes_client/tests/test_subject_set.py

Fixes #205
If the link slug wasn't already in the list of links, trying to set the
link would set an attribute on the `PanoptesObject` instead of creating an
entry in `raw['links']`.
This PR changes the setattr logic to make sure the slug _isn't_ an
attribute rather than checking it _is_ a link. This allows setting links
that the client doesn't already know about, but has the side effect of
allowing invalid links. This is actually a good thing, because invalid
links will be rejected by the API, whereas before they would have been
set as attributes and silently discarded on save.

Fix: Can't save new objects with individual links

---

setup.py

Not picked up in testing because `mock` pulls in the package.

Fix: Missing 'six' dependency

---

Dockerfile.dev
Dockerfile.dev2
Dockerfile.stable
Dockerfile.stable2

ensure the client can use python libmagic - ideally these would be pushed to dockerhub as offical images for reuse via jenkins file on master changes / releases
without the changes
```
>>> from panoptes_client import Panoptes, Project
Broken libmagic installation detected. The python-magic module is installed but can't be imported. Please check that both python-magic and the libmagic shared library are installed correctly. Uploading media other than images may not work.
```
with changes
```
>>> from panoptes_client import Panoptes, Project
>>> quit()
```

add install for libmagic

---

README.md

Suggested modification to README. The "git+git" URL form does not work unless SSH keys have been configured. The "git+https" form is more likely to work.

Updated pip GitHub URL

---

panoptes_client/subject.py
panoptes_client/workflow.py

Determining whether to save the workflow configuration relies on comparison between a potentially updated configuration dict and a copy of the original taken when the Workflow instance was created. Using assignment or even copy construction can (apparently not always) result in the "copy" in fact being a reference to the object which may be modified. This means that the two always compare equal and the config is never saved. Using copy.deepcopy solves this issue.

Deep copy of initial workflow config

---

panoptes_client/project.py

Waiting for the corresponding API update to be deployed before I can test `add_attached_image`.
I really wanted to add a reusable `AttachedImage` class, so attached images could be accessed/managed as normal linked objects, but the lack of a route to access them without the parent object's ID makes that difficult because of assumptions made in `PanoptesObject` (i.e. we'd need a route like `/api/attached_images/:attached_image_id` – maybe something to consider for the future).

Add attached image methods to Project

---

panoptes_client/panoptes.py
panoptes_client/subject.py

The header can exist for all PUT requests, as everything but Azure will ignore it. It's required to properly upload files/blobs to Azure Storage via a SAS-signed request

Add Azure header to all PUT requests

---

CHANGELOG.md
setup.py

Includes the Azure header on PUT requests for when the migration of data and infrastructure is finished on the API side.

Prepare 1.3 release

---

panoptes_client/project.py
panoptes_client/workflow.py

Rebased version of #236, but same goal: building directly from #222, expand editable dicts in workflow.py and project.py to include `Project.configuration`, `Workflow.retirement`, and `Workflow.tasks`.

Add support for all dict-type editable attributes (v2)

---

panoptes_client/subject.py
panoptes_client/workflow.py

Currently Drafting this Pr:
**Current Changes:**
- shortcut functions on the Workflow resource and the Subject resource to query SubjectWorkflowStatus (These were suggestions on this github issue https://github.com/zooniverse/panoptes-python-client/issues/231)
Not in this PR/changes, but I think it would be nice to have the ability to query SubjectWorkflowStatus by subject_set_id, (i.e. `Workflow.subject_set_status(subject_set_id=YOUR_SS_ID)`, but I think for this change to happen, would have to update the panoptes API route that queries SubjectWorkflowStatus to also be able to accept subject_set_id. Am I off base on this? Would love feedback.

Subjectworkflowstatus helpers

---

.github/workflows/publish-to-pypi.yml
.github/workflows/publish-to-test-pypi.yml

GH action configuration to twine upload to pypi on new releases. Most of this is following what Coleman set up on this PR https://github.com/zooniverse/aggregation-for-caesar/pull/445. Only difference is that I set it up on release instead of `workflow_dispatch`.  But I can change that if we want. 
- One thing, I'm unsure how to test this. So would love feedback or another set of eyes on this.

GH action on release 

---

panoptes_client/panoptes.py

avoid no logger handler warnings in python 2.7, https://stackoverflow.com/questions/44188270/no-handlers-could-be-found-for-logger

ensure logger handlers are setup

---

panoptes_client/project.py

Linked to https://github.com/zooniverse/panoptes/pull/3740
This PR adds the ability to copy a 'template' project using the API copy end point. 
Example Usage
``` python
project = Project.find(id)
copied_project = project.copy()
pp.pprint(copied_project.raw)
copied_project = project.copy('my new set for uploading')
pp.pprint(copied_project.raw)
```

Add copy method to Project resource

---

panoptes_client/subject.py

Closes #239
Initialize existing `Subject()` instances with a `_media_files` array whose length matches that of `locations` array and is filled with `None` elements. Also, add `locations` to `modified_attributes` when `add_location` is called. These two edits fixes issue where `add_location()` calls for existing subjects -- those that already have been saved with existing media `locations` -- was failing.

Fix media uploads for existing subjects

---

panoptes_client/caesar.py
panoptes_client/tests/test_workflow.py
panoptes_client/workflow.py

Updated `add_to_caesar` method to `save_to_caesar` which will check if workflow exists in caesar first, if it does, then update, if it doesn't exist in caesar, then create.

adding save  workflow to caesar method

---

docs/user_guide.rst

Same as #225, updating the direct-from-github `pip` install command to use HTTPS instead of no-longer-support `git+git` method.

Update Docs: use HTTPS for git-based install command

---

docs/panoptes_client.rst

Edit `panoptes_client.rst` to autopopulate Caesar entries on doc page. Builds on https://github.com/zooniverse/panoptes-python-client/pull/274/commits/59772ddb3ad8fedb6d888f28dd52d23989bbe44b.
Copied format of other classes, but did not confirm this fix works.

Autopopulate Caesar entries in docs

---

docs/panoptes_client.rst

Edit panoptes_client.rst to autopopulate Caesar entries on doc page. Builds on https://github.com/zooniverse/panoptes-python-client/commit/219a4789298cff1a95c43de20aac50a01609d830
ReadTheDocs was not correct; this should help.  Third try.

bug fix: doc links for caesar (v2)

---

panoptes_client/caesar.py

On initial go of getting caesar functionality to python client, I missed importing data extracts feature via the caesar module (can be done via workflow).

import ML data extracts from caesar module

---

docs/user_guide.rst
panoptes_client/__init__.py
panoptes_client/inaturalist.py
panoptes_client/tests/test_inaturalist.py

Adds a simple iNaturalist object that has a single method. That method sends a POST request to Panoptes that starts an iNat Observation import. It uses the base `Panoptes.client()` POST method, which includes authentication. 
~I've included two tests which are currently failing--I can't figure out why the mock isn't working. The SubjectSet test was the model and it sure seems to me that they that method should be stubbed and not actually trying to call out. It's a simple enough test that it might be easier to just remove it, but let me know if I'm missing something obvious.~
Tests are sorted, I forgot to remove some dev/debug stuff. Thanks @yuenmichelle1

Add iNaturalist class & import method

---

panoptes_client/subject_set.py

There have been a few soft crashes with subject uploads, leading to the question of whether the async subject upload was causing issues. I've added a new non-asynchronous save method which appears to be more stable.
One other issue was when Panoptes would throw a `409: Attempted to update a stale object: SubjectSet.` when updating subject sets with uploaded subjects. I've added a condition to the request to retry on a `409` error, which has fixed this issue.

Fixing 409 crashes

---

docs/user_guide.rst
panoptes_client/project_preferences.py

implement fetch_settings to project_preferences class

implement fetch_settings to project_preferences class

---

docs/user_guide.rst

Adding docs for Project Copier & Programmatic Data Exports, and reorganizing "Other examples" section into individual TOC items.

modify user guide to have Project copier and Data exports in other examples

---

panoptes_client/subject.py
panoptes_client/subject_set.py
panoptes_client/tests/test_subject_set.py

Closes https://github.com/zooniverse/panoptes-cli/issues/256
The issue: when `SubjectSet.metadata` attribute is edited, there is no check for changes in that field, so it is never added to `modified_attributes` set and therefore those edits were never pushed as a result of the `save()` call.
Following same solution as in #222 and #251 for workflow and project attributes:
- add code to initialize current vs original check of metadata dict in `set_raw` and `__init__` functions
- add check to `save()` to add metadata attribute to `modified_attributes` if contents are different
Note on change in treatment of `SubjectSet.metadata` field: I've changed `metadata` to a standalone key in `SubjectSet._edit_attributes` field as opposed to dict similar to `links` field.  The distinction between these …

Add support for SubjectSet metadata as editable attribute

---

docs/conf.py
panoptes_client/panoptes.py
panoptes_client/subject.py

Closes #305 
Following recommendations from the `pkg_resources` devs, I'm replacing its use for extracting package versions by swapping in the `importlib.metadata` package.

Remove pkg_resources dependency
