panoptes_client/__init__.py, panoptes_client/project_preferences.py
This adds ProjectPreferences to the client for #4
=> Add ProjectPreferences

panoptes_client/__init__.py, panoptes_client/classification.py
Potential WIP on account of the find method error below. That ID def exists, because I just grabbed it. I'm thinking that it might be a permissions issue because I'm not that user or a client with privileges sufficient to grab it. If that's the case, then this is ok.
`
>>> c = Classification.find('14019243')
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "panoptes_client/panoptes.py", line 277, in find
return cls.where(id=_id).next()
File "panoptes_client/panoptes.py", line 271, in where
return cls.paginated_results(*cls.get(_id, params=kwargs))
File "panoptes_client/panoptes.py", line 256, in get
headers
File "panoptes_client/panoptes.py", line 136, in get
return self.json_request('GET', path, params, headers)
File "panoptes_client/panoptes.py", line 127, in …
=> Added Classification

panoptes_client/panoptes.py, panoptes_client/subject_set.py
Adds `DELETE` method and add and remove subject links to subject-set for #4
=> Subject set links

panoptes_client/__init__.py, panoptes_client/project_preferences.py, panoptes_client/user.py
This adds the `User` model which inherits the `PanoptesObject` methods as well as the ability to fetch project preferences either by ids directly or using the `User` and `Project` models. For #4
=> Added User model. Find ProjectPreferences by User and Project object.

panoptes_client/panoptes.py
Closed #14. This allows someone to set environment variables in their bash profile for username, password, endpoint, and client id.
=> Add option for env vars for auth

panoptes_client/__init__.py, panoptes_client/panoptes.py, panoptes_client/set_member_subject.py, panoptes_client/subject.py, panoptes_client/subject_set.py
Also adds Subject.subject_sets() convenience function and adds option to
register arbitrary link slugs in LinkResolver.
=> Add SetMemberSubject class

panoptes_client/subject_set.py
It occurs to me that we should avoid trying to link too many of these in each request.
=> Submit subject links in batches in SubjectSet.add()

panoptes_client/panoptes.py
For #17 and supercedes #13. I've fixed this so that authenticating by client id and client secret is returning a bearer token, but I still am not able to do tasks that I expected to be able to such as adding and removing a subject link from a subject set. Going to dig into this a bit more, so labeling as WIP.
At some later point, I'd like to refactor to separate out concerns with the authentication, but want to get this working first.
=> oauth for client apps

panoptes_client/workflow.py
=> Add Workflow->SubjectSet linking

panoptes_client/panoptes.py
=> Only save links if it's been modified

panoptes_client/project_preferences.py
Changes http method to `POST` based on change in zooniverse/panoptes#1919
=> Change http method to post

panoptes_client/__init__.py, panoptes_client/set_member_subject.py, panoptes_client/subject.py
For #32. I don't think `SetMemberSubject` is needed for anything else.
=> Removed subject_sets method and SetMemberSubject

panoptes_client/project.py, panoptes_client/tests/test_project.py
when project can't be found by slug
Closes #36
Closes #45
=> Raise PanoptesAPIException instead of StopIteration

panoptes_client/subject_set.py
=> Batch requests in SubjectSet.remove

README.md
docs on listing subjects in a set, useful for people doing subject uploads via the api.
=> docs to list subjects in a subject_set

panoptes_client/panoptes.py
=> Add admin option

Dockerfile.dev, Dockerfile.stable, docker-compose.yml
=> Add Docker config

panoptes_client/panoptes.py
=> Fix setting endpoint in environment variable

panoptes_client/__init__.py, panoptes_client/collection.py
Closes #54 
This is pretty much copy and pasted from `SubjectSet`. We'll probably want to refactor at some point.
=> Add Collection

panoptes_client/classification.py, panoptes_client/collection.py, panoptes_client/panoptes.py, panoptes_client/project.py, panoptes_client/project_preferences.py, panoptes_client/subject_set.py, panoptes_client/workflow.py
=> Prefix HTTP request method names with http_

panoptes_client/collection.py, panoptes_client/subject_set.py, panoptes_client/utils.py, panoptes_client/workflow.py
=> Refactor iterable types checking and add numpy array

panoptes_client/exportable.py, panoptes_client/project.py, panoptes_client/workflow.py
Refactor exports into mixin and add to Workflow
=> Add per-Workflow exports

README.md
Add links to the wiki for more examples and add code on batch linking subjects to a set.
=> Update readme docs 

panoptes_client/utils.py
Sets don't support indexing, so convert them to lists.
=> Fix passing sets to batchable methods

Dockerfile.dev2, Dockerfile.stable2, docker-compose.yml, panoptes_client/classification.py, panoptes_client/collection.py, panoptes_client/exportable.py, panoptes_client/panoptes.py, panoptes_client/project.py, panoptes_client/project_preferences.py, panoptes_client/project_role.py, panoptes_client/subject.py, panoptes_client/subject_set.py, panoptes_client/tests/test_project.py, panoptes_client/user.py, panoptes_client/utils.py, panoptes_client/workflow.py, setup.py
=> Python 3 compatibility

README.md, panoptes_client/__init__.py, panoptes_client/set_member_subject.py, panoptes_client/subject_set.py, panoptes_client/tests/test_set_member_subject.py
Closes #60 assuming this is a sensible way to do this.
If I understand correctly, this will use a faster query, with the downside of needing a bunch of requests to actually fetch subject data.
@camallen I'd like to hear your opinion on this.
=> Use SetMemberSubject for SubjectSet.subjects()

docker-compose.yml, panoptes_client/subject.py, setup.py
Using python-magic for file type detection.
=> Add support for non-image media types

panoptes_client/subject.py
=> Fallback to imghdr for type detection if no libmagic

README.md
so people know how to upgrade their currently installed client to get new features.
=> add note on upgrading client

panoptes_client/project.py
=> Add methods for adding Project links

CHANGELOG.md
=> Update CHANGELOG.md for v1.0

panoptes_client/exportable.py
Closes #141
I don't think this was actually because of the gzip encoding after all. Looks like requests was just returning the decoded content as bytes rather than unicode.
=> Add CSV reader wrappers to exports

panoptes_client/__init__.py, panoptes_client/collection_role.py
Closes #134. I haven't gotten specific requirements yet, so this is just adding a base class for CollectionRole to inherit all the basic HTTP methods similar to ProjectRole.
=> Add the base class for CollectionRole

panoptes_client/panoptes.py, panoptes_client/user.py
Depends on zooniverse/Panoptes#2704
=> Make User.valid_user editable

panoptes_client/workflow.py
=> Add tasks and primary_language to Workflow._edit_attributes

panoptes_client/classification.py
=> Fix typo in documentation for Classification

panoptes_client/panoptes.py
=> Fix saving objects initialised from object links

panoptes_client/user.py
Fix the page size to be the same as the batch size for email and login
queries.
This is a workaround for zooniverse/Panoptes#2733
=> Fix: Work around bad User paging

panoptes_client/panoptes.py
To make debugging easier. It could be confusing getting an authentication
error some time after calling `connect` when you might assume it
authenticated successfully.
=> Log in immediately rather than waiting for first request

panoptes_client/subject.py
Also fixes calling Subject.save() when nothing has changed.
Closes #165
=> Fix saving subjects with updated metadata

panoptes_client/subject.py, setup.py
Forked from #173 to avoid conflicts, so can't be merged before that.
=> Use multiple threads to upload media for subjects which have multiple files

panoptes_client/panoptes.py
=> Fix linking to lists of objects

panoptes_client/panoptes.py, panoptes_client/subject.py
=> Add asynchronous subject creation

README.md, docs/user_guide.rst, panoptes_client/panoptes.py
- Mention that attributes are documented in the API docs.
- Explain lazy loading
- Add contributing section to README.md
- Mention which Python versions are supported
=> Additions to docs

panoptes_client/subject.py
=> Raise an exception if media mime type can't be determined

panoptes_client/workflow.py
Adds the `configuration` attribute to the `modified_attributes` set associated with the `Workflow` object if the configuration has been modified since the object was retrieved.
=> Save workflow configuration if changed.

.github/workflows/codeql-analysis.yml
=> enable gh security scanning

CHANGELOG.md, setup.py
There's about a year's worth of relatively small changes that we should finally release.
=> Prepare 1.2 release

docs/user_guide.rst, panoptes_client/workflow.py
**Changes**
- adding logic to unretire by subject ids
- adding logic t ounretire by subject set id
=> Allow unretiring subjects

panoptes_client/subject_set.py
Linked to the work in https://github.com/zooniverse/panoptes/pull/3719
Allow SubjectSet resource to generate their classification data exports
=> add exportable behaviour to SubjectSet class

CHANGELOG.md, setup.py
update setup.py to include description
update Changelog
=> Version  1.5

.github/workflows/run-tests.yml
run ci system via latest gh actions python setup
=> use latest python setup gh actions

panoptes_client/caesar.py
Resolves issue: https://github.com/zooniverse/panoptes-python-client/issues/292
=> Caesar connect respect connection env

panoptes_client/project.py
Add requirements to project copy doc
=> add extra documentation on requirrements for project copy

.readthedocs.yaml
Add readthedocs.yaml file to build the docs
=> add readthedocs.yaml file

docs/user_guide.rst, panoptes_client/project_preferences.py
Make the response of project preference fetch settings to return paginated data
=> paginate response from project preference fetch_settings

panoptes_client/subject.py, panoptes_client/tests/test_subject.py
Solves for these issues:
[Mime type assignment](https://github.com/zooniverse/panoptes-python-client/issues/320)
[Improve Mime typing](https://github.com/zooniverse/panoptes-python-client/issues/297)
=> add MIME type assignment and improve MIME typing on auto detection for subject locations

CHANGELOG.md, setup.py
Update change logs for new versio
=> update changelog and bump version

docs/user_guide.rst, panoptes_client/panoptes.py, panoptes_client/user.py
Add tracking of logged in user, making it easier to return user ID and other user information for that logged in user.
=> Track logged-in user, add convenience functions
